
services:
  - type: web
    name: smarttips-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python smarttips_bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
